//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSeekWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_company_job
    {
        public int jobId { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string position { get; set; }
        public int vacancy { get; set; }
        public Nullable<int> assigned_to { get; set; }
        public System.DateTime create_date { get; set; }
        public System.DateTime close_date { get; set; }
        public string status { get; set; }
    }
}
