//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSeekWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_personal_project
    {
        public int perprojectId { get; set; }
        public string title { get; set; }
        public string projectDesc { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime completed { get; set; }
        public int ownerId { get; set; }
        public int isWorkerProj { get; set; }
        public string privacy { get; set; }
    }
}
