//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSeekWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_requirements
    {
        public int requirementId { get; set; }
        public string experience { get; set; }
        public int skillId { get; set; }
        public int jobId { get; set; }
        public int projectId { get; set; }
    }
}
